config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

  resources :tasks
  resources :users

  get '/signup' => 'users#new'
  
  
end

app/models/task.rb
class Task < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :name, presence: true, length: {maximum: 50}
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX },
  		uniqueness: true
	has_secure_password
	validates :password, length: { minimum: 6 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

	def new	
	end

	def create
		@task = Task.new(task_params)

		@task.save
		redirect_to tasks_path
	end

	def index
		@tasks = Task.all
	end

	private
		def task_params
			params.require(:task).permit(:problem)
		end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "Welcome!"
  		redirect_to @user
  	else
  		render 'new'
  	end
  end

  def show
  	@user = User.find(params[:id])
  end

  def index
  	@users = User.all
  end

  private
	def user_params
	  params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
	def gravatar_for(user, options = { size: 50 })
		gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
		size = options[:size]
		gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
		image_tag(gravatar_url, alt: user.name, class: "gravatar")
	end
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<ul id="nav">
<li>
		<%= link_to 'Войти', 'signin' %> 
	</li>
	<li>
		<%= link_to 'Регистрация', 'signup' %>
	</li>
	<li>
		<%= link_to 'Пользователи', users_path %>
		<ul>
			<li><%= link_to 'Group1' %> </li>
			<li><%= link_to 'Group2' %></li>
			<li><%= link_to 'Group3' %></li>
			<li><%= link_to 'Group4' %></li>
		</ul>
	</li>
	<li>
		<%= link_to 'Задачи', tasks_path %> 
		<ul>
			<li><%= link_to 'Hometask 1' %></li>
			<li><%= link_to 'Hometask 2' %></li>
			<li><%= link_to 'Hometask 3' %></li>
			<li><%= link_to 'Hometask 4' %></li>
			<li><%= link_to 'Hometask 5' %></li>
		</ul>
	</li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>hwproj <%= yield(:title) %> </title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render 'layouts/header' %>

<% flash.each do |key, value| %>
  <i><h3> <%= value %> </h3></i>
<% end %>

<%= yield %>
<%= debug(params) if Rails.env.development? %>
</body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/tasks/index.html.erb
<h1>Задачи</h1>

<%= link_to 'Добавить задачу', new_task_path %> <br>

<ol>
  <% @tasks.each do |t| %>
    <li> <%= t.problem %> </li>
  <% end %>
</ol>

app/views/tasks/new.html.erb
<h1>Добавить задачу</h1>

<%= form_for :task, url: tasks_path do |f| %>
	<p>
		<%= f.label :problem %> <br>
		<%= f.text_area :problem %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/users/index.html.erb
<h1>Users</h1>

<% if @users.empty? %>
  <%= "No users yet." %>
<% end %>

<ul>
  <% for user in @users %>
  	<il> <%= gravatar_for(user, size: 24) %>
  	  <b> <%= link_to user.name, user %> </b> <%= user.email %> <br>
  	</il>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, 'Sign up') %>

<h1>Sign up</h1>

<%= form_for @user do |f| %>

  <%= render 'shared/error_messages' %>
<br>
  <%= f.label :name %>
  <%= f.text_field :name %>
<br>
  <%= f.label :email %>
  <%= f.text_field :email %>
<br>
  <%= f.label :password %>
  <%= f.password_field :password %>
<br>
  <%= f.label :password_confirmation, "Confirmation" %>
  <%= f.password_field :password_confirmation %>
<br>
  <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>

<% end %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>

<h1>
  <%= gravatar_for @user %>
  <%= @user.name %>
</h1>

app/views/welcome/index.html.erb
<h1>hwProj - Домашние работы</h1>